# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  allow-parallel-runners: true
  timeout: 5m
linters:
  default: none
  enable:
    - asasalint
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - dupl
          - goconst
          - gocyclo
          - unparam
          - errcheck
      - path: ^test/
        linters:
          - dupl
          - goconst
          - gocyclo
          - unparam
          - noctx
          - errcheck
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
