apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-manager-role" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
rules:
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - runnerclusters
  - runnermachines
  - runnernodepools
  - runnerscalesets
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - runnerclusters/status
  - runnermachines/status
  - runnernodepools/status
  - runnerscalesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - ephemeralrunners/status
  - ephemeralrunnersets/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - runnerclusters/finalizers
  - runnermachines/finalizers
  - runnernodepools/finalizers
  - runnerscalesets/finalizers
  - ephemeralrunners/finalizers
  verbs:
  - update
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - ephemeralrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharc.walnuts.dev
  resources:
  - ephemeralrunnersets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  - nodes
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-manager-rolebinding" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-manager-role" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "smart-hibernatable-actions-runner-controller.fullname" .) }}
  namespace: {{ .Release.Namespace }}
