{{- if and (eq .Values.telemetry.metrics.exporter "prometheus") .Values.telemetry.prometheus.service.enabled .Values.telemetry.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "smart-hibernatable-actions-runner-controller.fullname" . }}
  labels:
    {{- include "smart-hibernatable-actions-runner-controller.labels" . | nindent 4 }}
    {{- with .Values.telemetry.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.telemetry.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.telemetry.prometheus.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "smart-hibernatable-actions-runner-controller.selectorLabels" . | nindent 6 }}
{{- end }}
