{{- if and (eq .Values.telemetry.metrics.exporter "prometheus") .Values.telemetry.prometheus.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "smart-hibernatable-actions-runner-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.telemetry.prometheus.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "smart-hibernatable-actions-runner-controller.selectorLabels" . | nindent 4 }}
{{- end }}
