{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-selfsigned-issuer" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "smart-hibernatable-actions-runner-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-serving-cert" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "smart-hibernatable-actions-runner-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  dnsNames:
  - {{ printf "%s-webhook-service" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
  - {{ printf "%s-webhook-service" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ printf "%s-selfsigned-issuer" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
  secretName: {{ .Values.webhook.certManager.certSecretName | default (printf "%s-webhook-cert" (include "smart-hibernatable-actions-runner-controller.fullname" .)) | trunc 63 | trimSuffix "-" }}
{{- end }}
