{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-webhook-service" (include "smart-hibernatable-actions-runner-controller.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "smart-hibernatable-actions-runner-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port | default 9443 }}
  selector:
    app.kubernetes.io/name: {{ include "smart-hibernatable-actions-runner-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
