{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gha-baremetal-operator.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/name: {{ include "gha-baremetal-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port | default 9443 }}
  selector:
    app.kubernetes.io/name: {{ include "gha-baremetal-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
