apiVersion: gha.walnuts.dev/v1alpha1
kind: RunnerMachine
metadata:
  name: gha-amd64-01
spec:
  clusterRef:
    name: gha-amd64
  nodePoolRef:
    name: amd64
  nodeName: gha-amd64-01
  powerPolicy: OnDemand
  priority: 100
  capacity:
    runnerSlots: 2
  drain:
    timeout: 10m
  redfish:
    endpoint: https://192.168.10.50
    systemID: "1"
    credentialsSecretRef:
      name: gha-amd64-01-redfish
    tls:
      caSecretRef:
        name: ilo-ca
        key: ca.crt
      insecureSkipVerify: false
    power:
      shutdown:
        timeout: 3m
        timeoutPolicy: Abort
