apiVersion: sharc.walnuts.dev/v1alpha1
kind: EphemeralRunnerSet
metadata:
  name: sample-medium-amd64
spec:
  scaleSetRef:
    name: sample-medium-amd64
  replicas: 1
  runner:
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.321.0
            resources:
              requests:
                cpu: "4"
                memory: 8Gi
