//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralRunner) DeepCopyInto(out *EphemeralRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralRunner.
func (in *EphemeralRunner) DeepCopy() *EphemeralRunner {
	if in == nil {
		return nil
	}
	out := new(EphemeralRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralRunnerList) DeepCopyInto(out *EphemeralRunnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EphemeralRunner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralRunnerList.
func (in *EphemeralRunnerList) DeepCopy() *EphemeralRunnerList {
	if in == nil {
		return nil
	}
	out := new(EphemeralRunnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralRunnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralRunnerSpec) DeepCopyInto(out *EphemeralRunnerSpec) {
	*out = *in
	out.ScaleSetRef = in.ScaleSetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralRunnerSpec.
func (in *EphemeralRunnerSpec) DeepCopy() *EphemeralRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralRunnerStatus) DeepCopyInto(out *EphemeralRunnerStatus) {
	*out = *in
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningAttemptStatus)
		(*in).DeepCopyInto(*out)
	}
	in.GitHub.DeepCopyInto(&out.GitHub)
	out.RemotePod = in.RemotePod
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = new(RunnerFailureStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralRunnerStatus.
func (in *EphemeralRunnerStatus) DeepCopy() *EphemeralRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(EphemeralRunnerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRunnerStatus) DeepCopyInto(out *GitHubRunnerStatus) {
	*out = *in
	if in.CompletedObservedAt != nil {
		in, out := &in.CompletedObservedAt, &out.CompletedObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRunnerStatus.
func (in *GitHubRunnerStatus) DeepCopy() *GitHubRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRunnerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubScaleSetSpec) DeepCopyInto(out *GitHubScaleSetSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubScaleSetSpec.
func (in *GitHubScaleSetSpec) DeepCopy() *GitHubScaleSetSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubScaleSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubStatisticsStatus) DeepCopyInto(out *GitHubStatisticsStatus) {
	*out = *in
	if in.LastStatisticsTime != nil {
		in, out := &in.LastStatisticsTime, &out.LastStatisticsTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubStatisticsStatus.
func (in *GitHubStatisticsStatus) DeepCopy() *GitHubStatisticsStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubStatisticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerSpec) DeepCopyInto(out *ListenerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerSpec.
func (in *ListenerSpec) DeepCopy() *ListenerSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerStatus) DeepCopyInto(out *ListenerStatus) {
	*out = *in
	if in.LastConnectedTime != nil {
		in, out := &in.LastConnectedTime, &out.LastConnectedTime
		*out = (*in).DeepCopy()
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerStatus.
func (in *ListenerStatus) DeepCopy() *ListenerStatus {
	if in == nil {
		return nil
	}
	out := new(ListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineMaintenanceSpec) DeepCopyInto(out *MachineMaintenanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineMaintenanceSpec.
func (in *MachineMaintenanceSpec) DeepCopy() *MachineMaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MachineMaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinePlanStatus) DeepCopyInto(out *MachinePlanStatus) {
	*out = *in
	if in.DrainStartedAt != nil {
		in, out := &in.DrainStartedAt, &out.DrainStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinePlanStatus.
func (in *MachinePlanStatus) DeepCopy() *MachinePlanStatus {
	if in == nil {
		return nil
	}
	out := new(MachinePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineQuarantineStatus) DeepCopyInto(out *MachineQuarantineStatus) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
	if in.HealthySince != nil {
		in, out := &in.HealthySince, &out.HealthySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineQuarantineStatus.
func (in *MachineQuarantineStatus) DeepCopy() *MachineQuarantineStatus {
	if in == nil {
		return nil
	}
	out := new(MachineQuarantineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerOperationStatus) DeepCopyInto(out *PowerOperationStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.LastAttemptAt.DeepCopyInto(&out.LastAttemptAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerOperationStatus.
func (in *PowerOperationStatus) DeepCopy() *PowerOperationStatus {
	if in == nil {
		return nil
	}
	out := new(PowerOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningAttemptStatus) DeepCopyInto(out *ProvisioningAttemptStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.JITGeneratedAt != nil {
		in, out := &in.JITGeneratedAt, &out.JITGeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningAttemptStatus.
func (in *ProvisioningAttemptStatus) DeepCopy() *ProvisioningAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(ProvisioningAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishHealthStatus) DeepCopyInto(out *RedfishHealthStatus) {
	*out = *in
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
	if in.NextProbeTime != nil {
		in, out := &in.NextProbeTime, &out.NextProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishHealthStatus.
func (in *RedfishHealthStatus) DeepCopy() *RedfishHealthStatus {
	if in == nil {
		return nil
	}
	out := new(RedfishHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishPowerSpec) DeepCopyInto(out *RedfishPowerSpec) {
	*out = *in
	if in.ShutdownTimeout != nil {
		in, out := &in.ShutdownTimeout, &out.ShutdownTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ForceOffAfter != nil {
		in, out := &in.ForceOffAfter, &out.ForceOffAfter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishPowerSpec.
func (in *RedfishPowerSpec) DeepCopy() *RedfishPowerSpec {
	if in == nil {
		return nil
	}
	out := new(RedfishPowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishSpec) DeepCopyInto(out *RedfishSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	in.TLS.DeepCopyInto(&out.TLS)
	in.Power.DeepCopyInto(&out.Power)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishSpec.
func (in *RedfishSpec) DeepCopy() *RedfishSpec {
	if in == nil {
		return nil
	}
	out := new(RedfishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishTLSSpec) DeepCopyInto(out *RedfishTLSSpec) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishTLSSpec.
func (in *RedfishTLSSpec) DeepCopy() *RedfishTLSSpec {
	if in == nil {
		return nil
	}
	out := new(RedfishTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotePodStatus) DeepCopyInto(out *RemotePodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotePodStatus.
func (in *RemotePodStatus) DeepCopy() *RemotePodStatus {
	if in == nil {
		return nil
	}
	out := new(RemotePodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerCluster) DeepCopyInto(out *RunnerCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerCluster.
func (in *RunnerCluster) DeepCopy() *RunnerCluster {
	if in == nil {
		return nil
	}
	out := new(RunnerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerClusterList) DeepCopyInto(out *RunnerClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerClusterList.
func (in *RunnerClusterList) DeepCopy() *RunnerClusterList {
	if in == nil {
		return nil
	}
	out := new(RunnerClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerClusterReadinessSpec) DeepCopyInto(out *RunnerClusterReadinessSpec) {
	*out = *in
	if in.APIRequestTimeout != nil {
		in, out := &in.APIRequestTimeout, &out.APIRequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeReadyTimeout != nil {
		in, out := &in.NodeReadyTimeout, &out.NodeReadyTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerClusterReadinessSpec.
func (in *RunnerClusterReadinessSpec) DeepCopy() *RunnerClusterReadinessSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerClusterReadinessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerClusterSpec) DeepCopyInto(out *RunnerClusterSpec) {
	*out = *in
	in.KubeconfigSecretRef.DeepCopyInto(&out.KubeconfigSecretRef)
	in.Readiness.DeepCopyInto(&out.Readiness)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerClusterSpec.
func (in *RunnerClusterSpec) DeepCopy() *RunnerClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerClusterStatus) DeepCopyInto(out *RunnerClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerClusterStatus.
func (in *RunnerClusterStatus) DeepCopy() *RunnerClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerFailureStatus) DeepCopyInto(out *RunnerFailureStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerFailureStatus.
func (in *RunnerFailureStatus) DeepCopy() *RunnerFailureStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerFailureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachine) DeepCopyInto(out *RunnerMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachine.
func (in *RunnerMachine) DeepCopy() *RunnerMachine {
	if in == nil {
		return nil
	}
	out := new(RunnerMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachineCapacity) DeepCopyInto(out *RunnerMachineCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachineCapacity.
func (in *RunnerMachineCapacity) DeepCopy() *RunnerMachineCapacity {
	if in == nil {
		return nil
	}
	out := new(RunnerMachineCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachineKubernetesStatus) DeepCopyInto(out *RunnerMachineKubernetesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachineKubernetesStatus.
func (in *RunnerMachineKubernetesStatus) DeepCopy() *RunnerMachineKubernetesStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerMachineKubernetesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachineList) DeepCopyInto(out *RunnerMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachineList.
func (in *RunnerMachineList) DeepCopy() *RunnerMachineList {
	if in == nil {
		return nil
	}
	out := new(RunnerMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachineSpec) DeepCopyInto(out *RunnerMachineSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.Capacity = in.Capacity
	in.Redfish.DeepCopyInto(&out.Redfish)
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MachineMaintenanceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachineSpec.
func (in *RunnerMachineSpec) DeepCopy() *RunnerMachineSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerMachineStatus) DeepCopyInto(out *RunnerMachineStatus) {
	*out = *in
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(PowerOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RedfishHealth != nil {
		in, out := &in.RedfishHealth, &out.RedfishHealth
		*out = new(RedfishHealthStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Kubernetes = in.Kubernetes
	if in.Quarantine != nil {
		in, out := &in.Quarantine, &out.Quarantine
		*out = new(MachineQuarantineStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastPowerTransitionTime != nil {
		in, out := &in.LastPowerTransitionTime, &out.LastPowerTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerMachineStatus.
func (in *RunnerMachineStatus) DeepCopy() *RunnerMachineStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerNodePool) DeepCopyInto(out *RunnerNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerNodePool.
func (in *RunnerNodePool) DeepCopy() *RunnerNodePool {
	if in == nil {
		return nil
	}
	out := new(RunnerNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerNodePoolList) DeepCopyInto(out *RunnerNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerNodePoolList.
func (in *RunnerNodePoolList) DeepCopy() *RunnerNodePoolList {
	if in == nil {
		return nil
	}
	out := new(RunnerNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerNodePoolScalingSpec) DeepCopyInto(out *RunnerNodePoolScalingSpec) {
	*out = *in
	if in.ScaleDownDelay != nil {
		in, out := &in.ScaleDownDelay, &out.ScaleDownDelay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerNodePoolScalingSpec.
func (in *RunnerNodePoolScalingSpec) DeepCopy() *RunnerNodePoolScalingSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerNodePoolScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerNodePoolSpec) DeepCopyInto(out *RunnerNodePoolSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.MachineSelector.DeepCopyInto(&out.MachineSelector)
	in.Scaling.DeepCopyInto(&out.Scaling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerNodePoolSpec.
func (in *RunnerNodePoolSpec) DeepCopy() *RunnerNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerNodePoolStatus) DeepCopyInto(out *RunnerNodePoolStatus) {
	*out = *in
	if in.IdleSince != nil {
		in, out := &in.IdleSince, &out.IdleSince
		*out = (*in).DeepCopy()
	}
	if in.DesiredMachines != nil {
		in, out := &in.DesiredMachines, &out.DesiredMachines
		*out = make([]MachinePlanStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerNodePoolStatus.
func (in *RunnerNodePoolStatus) DeepCopy() *RunnerNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerScaleSet) DeepCopyInto(out *RunnerScaleSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerScaleSet.
func (in *RunnerScaleSet) DeepCopy() *RunnerScaleSet {
	if in == nil {
		return nil
	}
	out := new(RunnerScaleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerScaleSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerScaleSetList) DeepCopyInto(out *RunnerScaleSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerScaleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerScaleSetList.
func (in *RunnerScaleSetList) DeepCopy() *RunnerScaleSetList {
	if in == nil {
		return nil
	}
	out := new(RunnerScaleSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerScaleSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerScaleSetScalingSpec) DeepCopyInto(out *RunnerScaleSetScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerScaleSetScalingSpec.
func (in *RunnerScaleSetScalingSpec) DeepCopy() *RunnerScaleSetScalingSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerScaleSetScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerScaleSetSpec) DeepCopyInto(out *RunnerScaleSetSpec) {
	*out = *in
	out.GitHub = in.GitHub
	out.NodePoolRef = in.NodePoolRef
	out.Scaling = in.Scaling
	in.Listener.DeepCopyInto(&out.Listener)
	in.Runner.DeepCopyInto(&out.Runner)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerScaleSetSpec.
func (in *RunnerScaleSetSpec) DeepCopy() *RunnerScaleSetSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerScaleSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerScaleSetStatus) DeepCopyInto(out *RunnerScaleSetStatus) {
	*out = *in
	in.GitHub.DeepCopyInto(&out.GitHub)
	in.Listener.DeepCopyInto(&out.Listener)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerScaleSetStatus.
func (in *RunnerScaleSetStatus) DeepCopy() *RunnerScaleSetStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerScaleSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerTemplateSpec) DeepCopyInto(out *RunnerTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerTemplateSpec.
func (in *RunnerTemplateSpec) DeepCopy() *RunnerTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
