apiVersion: v2
name: smart-hibernatable-actions-runner-controller
description: A Kubernetes Operator to autoscale bare-metal GitHub Actions runners via Redfish
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/walnuts1018/smart-hibernatable-actions-runner-controller
sources:
  - https://github.com/walnuts1018/smart-hibernatable-actions-runner-controller
maintainers:
  - name: walnuts1018
